name: CI for code push in PS-XT

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: npm install, build and test
        run: |
          npm install
          npm run build:prod --if-present
          npm test
